


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.users (id,name,email,rolle)
  values (new.id,new.raw_user_meta_data->>'full_name', new.email, new.raw_user_meta_data->>'rolle');
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."notiz" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "owner_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "is_privat" boolean DEFAULT false NOT NULL,
    "title" "text",
    "notiz_text" "text",
    "notiz_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    CONSTRAINT "Notiz_Title_check" CHECK (("length"("title") < 50)),
    CONSTRAINT "Notiz_is_privat_check" CHECK (("is_privat" = ANY (ARRAY[true, false]))),
    CONSTRAINT "notiz_notiz_text_check" CHECK (("length"("notiz_text") < 1000))
);


ALTER TABLE "public"."notiz" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."shared_notiz" (
    "id" bigint NOT NULL,
    "sent_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "sender_id" "uuid" DEFAULT "auth"."uid"(),
    "receiver_id" "uuid" DEFAULT "auth"."uid"(),
    "notiz_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."shared_notiz" OWNER TO "postgres";


ALTER TABLE "public"."shared_notiz" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."shared_notiz_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "registered_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "email" "text" DEFAULT '''@MCT''::text'::"text" NOT NULL,
    "rolle" smallint,
    "name" "text",
    CONSTRAINT "users_name_check" CHECK (("length"("name") < 100)),
    CONSTRAINT "users_rolle_check" CHECK ((("rolle" = 1) OR ("rolle" = 2) OR ("rolle" = NULL::smallint)))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notiz"
    ADD CONSTRAINT "notiz_notiz_id_key" UNIQUE ("notiz_id");



ALTER TABLE ONLY "public"."notiz"
    ADD CONSTRAINT "notiz_pkey" PRIMARY KEY ("notiz_id");



ALTER TABLE ONLY "public"."shared_notiz"
    ADD CONSTRAINT "shared_notiz_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."shared_notiz"
    ADD CONSTRAINT "shared_notiz_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."notiz"
    ADD CONSTRAINT "Notiz_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "Users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shared_notiz"
    ADD CONSTRAINT "shared_notiz_notiz_id_fkey" FOREIGN KEY ("notiz_id") REFERENCES "public"."notiz"("notiz_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shared_notiz"
    ADD CONSTRAINT "shared_notiz_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shared_notiz"
    ADD CONSTRAINT "shared_notiz_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."notiz" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shared_notiz" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."users";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."notiz" TO "anon";
GRANT ALL ON TABLE "public"."notiz" TO "authenticated";
GRANT ALL ON TABLE "public"."notiz" TO "service_role";



GRANT ALL ON TABLE "public"."shared_notiz" TO "anon";
GRANT ALL ON TABLE "public"."shared_notiz" TO "authenticated";
GRANT ALL ON TABLE "public"."shared_notiz" TO "service_role";



GRANT ALL ON SEQUENCE "public"."shared_notiz_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."shared_notiz_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."shared_notiz_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


